apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  namespace: user-namespace

spec:
  replicas: 2
  selector:
    matchLabels:
      app: user

  template:
    metadata:
      labels:
        app: user

    spec:
      containers:
        - name: user
          image: ayushi2312/user-insta
          ports:
            - containerPort: 3002