kind: Service
apiVersion: v1
metadata: 
  name: user-services
  namespace: user-namespace
spec:
  selector:
    app: user
  ports: 
   - protocol: TCP
     port: 80
     targetPort: 3002
  type: NodePort
