kind: Service
apiVersion: v1
metadata: 
  name: front-services
  namespace: front-namespace
spec:
  selector:
    app: front
  ports: 
   - protocol: TCP
     port: 80
     targetPort: 3000
  type: NodePort
