kind: Service
apiVersion: v1
metadata: 
  name: media-services
  namespace: media-namespace
spec:
  selector:
    app: media
  ports: 
   - protocol: TCP
     port: 80
     targetPort: 3004
  type: NodePort
