kind: Service
apiVersion: v1
metadata: 
  name: auth-services
  namespace: auth-namespace
spec:
  selector:
    app: auth
  ports: 
   - protocol: TCP
     port: 80
     targetPort: 3001
  type: NodePort
